package org.springframework.bytebuddy.bytecode;

/**
 * Abstract base class for dynamically generated Spring MVC endpoint classes.
 * This class serves as the superclass for all classes generated by
 * {@link EndpointApiBuilder} or {@link ReactiveHandlerBuilder} using
 * the ByteBuddy code generation library.
 *
 * <p>Instances of subclasses of this type are created at runtime and
 * represent dynamically constructed controller endpoints that can be
 * registered within a Spring application context.</p>
 *
 * @author [@Loong Wan](https://github.com/loong10k)
 * @since 3.0.0
 * @see EndpointApiBuilder
 * @see ReactiveHandlerBuilder
 */
public abstract class EndpointApi {

}
